jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

-     - name: Install dependencies
-       run: npm install puppeteer-core
+     - name: Install dependencies
+       run: npm install puppeteer

      - name: Run scraper and update CSV
        run: |
          node fetch.js

      - name: Commit updated CSV
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update fare.csv
          file_pattern: fare.csv
